#!/usr/bin/env php
<?php

/*
 * Generated by Humbug Box 4.3.8@5534406.
 *
 * @link https://github.com/humbug/box
 */

Phar::mapPhar('app-fixtures-alias.phar');

// default stub template @generated by BOX Manifest

$withManifest = array_search('--manifest', $argv);
$withoutAnsi = array_search('--no-ansi', $argv);

if ($withManifest !== false) {
    $resources = (($argc - 1 > $withManifest) && !str_starts_with($argv[$withManifest + 1], '-')) ? [$argv[$withManifest + 1]] : ['manifest.txt', 'manifest.xml', 'sbom.xml', 'sbom.json'];

    foreach ($resources as $resource) {
        $filename = "phar://app-fixtures-alias.phar/{$resource}";
        if (file_exists($filename)) {
            $manifest = file_get_contents($filename);
            if ($withoutAnsi !== false) {
                $manifest = preg_replace('#\\x1b[[][^A-Za-z]*[A-Za-z]#', '', $manifest);
            }
            echo $manifest, PHP_EOL;
            exit(0);
        } elseif (count($resources) === 1) {
            echo sprintf('Manifest "%s" is not available in this PHP Archive.', $resource), PHP_EOL;
            exit(2);
        }
    }
    echo 'No manifest found in this PHP Archive', PHP_EOL;
    exit(1);
}


require 'phar://app-fixtures-alias.phar/.box/bin/check-requirements.php';

require 'phar://app-fixtures-alias.phar/index.php';

__HALT_COMPILER(); ?>
