#!/usr/bin/env php
<?php
// app-fixtures-stub.php
/*
 * Generated by Humbug Box 4.3.8@5534406.
 *
 * @link https://github.com/humbug/box
 */

Phar::mapPhar('app-fixtures-alias.phar');

if ($argc > 1 && $argv[1] === '--manifest') {
    $resources = ($argc > 2 && !str_starts_with($argv[2], '-')) ? [$argv[2]] : ['manifest.txt', 'manifest.xml', 'sbom.xml', 'sbom.json'];

    foreach ($resources as $resource) {
        $filename = "phar://app-fixtures-alias.phar/{$resource}";
        if (file_exists($filename)) {
            echo file_get_contents($filename), PHP_EOL;
            $status = 0;
            break;
        } elseif (count($resources) === 1) {
            echo sprintf('Manifest "%s" is not available in this PHP Archive.', $resource), PHP_EOL;
            $status = 1;
            break;
        }
    }
    exit($status);
}

require 'phar://app-fixtures-alias.phar/.box/bin/check-requirements.php';
require 'phar://app-fixtures-alias.phar/index.php';

__HALT_COMPILER(); ?>
