---
site_name: BOX Manifest
site_url: https://llaville.github.io/box-manifest
repo_url: https://github.com/llaville/box-manifest # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
site_author: Laurent Laville
edit_uri: "" # hide edit button -- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button
theme:
    name: material
    icon:
        logo: material/zip-box
    palette: # Color palette toggle -- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
        # editorconfig-checker-disable
        - scheme: default
          primary: amber
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
        # editorconfig-checker-enable
    features:
        - navigation.instant # Instant loading -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
        - navigation.tabs # Navigation tabs -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
        - navigation.indexes # Section index pages -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
        - navigation.top # Back-To-Top button -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
        - content.code.copy # Code copy button -- https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
#plugins:
    #- asciinema-player # https://github.com/pa-decarvalho/mkdocs-asciinema-player
markdown_extensions:
    - attr_list
    - md_in_html # https://squidfunk.github.io/mkdocs-material/reference/grids/
    - pymdownx.highlight:  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
          use_pygments: true
          pygments_lang_class: true
    - pymdownx.tabbed: # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#content-tabs
          alternate_style: true
    - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
    - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#emoji
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - github-callouts
nav:
    - "Home": README.md
    - "Installation": installation.md
    - "Getting-Started": getting-started.md
    - "Contributing": contributing.md
