<?php

declare(strict_types=1);

/**
 * This file is part of the BoxManifest package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Bartlett\BoxManifest\Helper;

use Fidry\Console\IO;

use KevinGH\Box\Configuration\NoConfigurationFound;
use KevinGH\Box\Console\ConfigurationLocator;
use KevinGH\Box\Json\Json;

use Seld\JsonLint\ParsingException;

use Symfony\Component\Filesystem\Path;

use Webmozart\Assert\Assert;

use stdClass;

use function array_merge;
use function dirname;
use function file_exists;
use function getcwd;
use function implode;
use function is_bool;
use function is_string;
use function property_exists;
use function realpath;

/**
 * @author Laurent Laville
 * @since Release 4.1.0
 */
final class BoxConfigurationHelper
{
    public const NO_CONFIG_OPTION = 'no-config';
    public const CONFIG_PARAM = 'config';

    private const BASE_PATH_KEY = 'base-path';
    private const MAIN_KEY = 'main';
    private const DEFAULT_MAIN_SCRIPT = 'index.php';
    private const CHECK_REQUIREMENTS_KEY = 'check-requirements';

    private stdClass $rawConfig;

    private ?string $configPath = null;

    /**
     * @throws ParsingException
     */
    public function __construct(
        IO $io,
        ?string $boxManifestVersion = null,
        Json $json = new Json(),
    ) {
        $assocConfig = [];

        // @link https://box-project.github.io/box/configuration/#alias-alias
        $assocConfig['alias'] = 'box-auto-generated-alias.phar';

        // By default, the Box Manifest banner is used.
        // @link https://box-project.github.io/box/configuration/#banner-banner
        $assocConfig['banner'] = 'Generated by BOX Manifest ' . ($boxManifestVersion ?? '@dev') . "\n\n"
            . '@link https://github.com/llaville/box-manifest'
        ;
        // By default, this line is used
        // @link https://box-project.github.io/box/configuration/#shebang-shebang
        $assocConfig['shebang'] = '#!/usr/bin/env php';

        // @link https://box-project.github.io/box/configuration/#intercept-intercept
        $assocConfig['intercept'] = false;

        // @link https://box-project.github.io/box/configuration/#check-requirements-check-requirements
        $assocConfig[self::CHECK_REQUIREMENTS_KEY] = true;

        // @link https://box-project.github.io/box/configuration/#map-map
        $assocConfig['map'] = [];

        if (false === $io->getTypedOption(self::NO_CONFIG_OPTION)->asBoolean()) {
            $this->configPath = $this->getConfigPath($io);
        }

        if (null !== $this->configPath) {
            /** @var array<string, mixed> $fileConfig */
            $fileConfig = $json->decodeFile($this->configPath, true);
            $assocConfig = array_merge($assocConfig, $fileConfig);
        }

        // @link https://box-project.github.io/box/configuration/#base-path-base-path
        $basePath = $assocConfig[self::BASE_PATH_KEY] ?? null;
        // try to resolve it
        $basePath = $this->retrieveBasePath($this->configPath, $basePath); // @phpstan-ignore argument.type
        $assocConfig[self::BASE_PATH_KEY] = $basePath;

        $composerJsonPath = $assocConfig[self::BASE_PATH_KEY] . '/composer.json';

        $firstBin = null;

        if (file_exists($composerJsonPath)) {
            /** @var array<string, mixed> $decodedComposerJson */
            $decodedComposerJson = $json->decodeFile($composerJsonPath, true);
            $bin = $decodedComposerJson['bin'] ?? [];
            $firstBin = current((array) $bin);
            $firstBin = $firstBin ?: null;
        }

        $main = $assocConfig[self::MAIN_KEY] ?? null;

        if (is_bool($main)) {
            Assert::false(
                $main,
                'Cannot "enable" a main script: either disable it with `false` or give the main script file path.',
            );
        } else {
            // @link https://box-project.github.io/box/configuration/#main-main
            // @phpstan-ignore-next-line
            $assocConfig[self::MAIN_KEY] = $this->retrieveMainScriptPath($basePath, $main, $firstBin);
        }

        $this->rawConfig = (object) $assocConfig;
    }

    public function dump(): stdClass
    {
        return $this->rawConfig;
    }

    public function getConfigurationFile(): ?string
    {
        return $this->configPath;
    }

    public function getMainScript(): ?string
    {
        if (is_string($this->rawConfig->main)) {
            return $this->rawConfig->main;
        }

        return null;
    }

    public function getAlias(): string
    {
        return $this->rawConfig->alias;
    }

    public function getBanner(): string
    {
        $banner = '';
        if (property_exists($this->rawConfig, 'banner')) {
            $banner = $this->rawConfig->banner;
        }
        if (is_string($banner)) {
            return $banner;
        }
        return implode("\n", $banner);
    }

    public function getShebang(): string
    {
        if (property_exists($this->rawConfig, 'shebang')) {
            return $this->rawConfig->shebang;
        }
        return '';
    }

    /**
     * @return array<int, array<string, string>>
     */
    public function getMap(): array
    {
        return $this->rawConfig->map;
    }

    public function withInterceptFileFunctions(): bool
    {
        return $this->rawConfig->intercept;
    }

    public function withCheckRequirements(): bool
    {
        return $this->rawConfig->{self::CHECK_REQUIREMENTS_KEY};
    }

    private function getConfigPath(IO $io): ?string
    {
        try {
            /** @var string $configPath */
            $configPath = $io->getInput()->getOption(self::CONFIG_PARAM);
            $configPath ??= ConfigurationLocator::findDefaultPath();
        } catch (NoConfigurationFound) {
            return null;
        }
        return $configPath;
    }

    private function retrieveBasePath(?string $file = null, ?string $basePath = null): string
    {
        if (null === $file) {
            return getcwd(); // @phpstan-ignore return.type
        }

        if (null === $basePath) {
            $basePath = dirname($file);
        }

        $basePath = trim($basePath);

        Assert::directory(
            $basePath,
            'The base path %s is not a directory or does not exist.',
        );

        return realpath($basePath); // @phpstan-ignore return.type
    }

    private function retrieveMainScriptPath(string $basePath, ?string $main = null, ?string $firstBin = null): ?string
    {
        if (null !== $firstBin) {
            $firstBin = $this->normalizePath($firstBin, $basePath);
        }

        if (null !== $main) {
            $main = $this->normalizePath($main, $basePath);
        } else {
            $main = $firstBin ?? $this->normalizePath(self::DEFAULT_MAIN_SCRIPT, $basePath);
        }

        if (null === $main) { // @phpstan-ignore identical.alwaysFalse
            return null;
        }

        Assert::file($main);

        return $main;
    }

    private function normalizePath(string $file, string $basePath): string
    {
        return Path::makeRelative(trim($file), $basePath);
    }
}
