name: Docker

on:
    workflow_dispatch:
    push:
        branches:
            - 'master'
            - '3.x'

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v3
            -
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.1"
                    extensions: zlib, phar, openssl, pcre, tokenizer, filter
                    ini-values: phar.readonly=0
            -
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Build and push Docker images
                uses: docker/build-push-action@v4
                with:
                    platforms: linux/amd64
                    push: true
                    tags: |
                        ghcr.io/llaville/box-manifest:v3
