---
name: Release

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    tests:
        uses: ./.github/workflows/unit-tests.yml

    build:
        needs: tests

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - 8.1

        steps:
            -   # Git Checkout
                name: Checkout
                uses: actions/checkout@v3

            -   # Setup PHP runtime
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   # Install Composer dependencies
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"

            -   # Build the current release with artifacts (php archive)
                name: Build Release Artifacts -- Manifest
                run: |
                    ${{ github.workspace }}/bin/box-manifest -c box.json --output-file=manifest-sbom.xml
                    ${{ github.workspace }}/bin/box-manifest -c box.json --output-file=manifest-manifest.txt --format ansi
                    ${{ github.workspace }}/bin/box-stub -c box.json --output-file=manifest-stub.php --resource manifest-manifest.txt --resource manifest.sbom.xml
                    ${{ github.workspace }}/bin/box-compile -c box.json.dist
            -
                name: Build Release Artifacts -- Stub
                run: |
                    ${{ github.workspace }}/bin/box-manifest -c box-stub.json --output-file=stub-sbom.xml
                    ${{ github.workspace }}/bin/box-manifest -c box-stub.json --output-file=stub-manifest.txt --format ansi
                    ${{ github.workspace }}/bin/box-stub -c box-stub.json --output-file=stub-stub.php --resource stub-manifest.txt --resource stub.sbom.xml
                    ${{ github.workspace }}/bin/box-compile -c box-stub.json.dist
            -
                name: Build Release Artifacts -- Compile
                run: |
                    ${{ github.workspace }}/bin/box-manifest -c box-compile.json --output-file=compile-sbom.xml
                    ${{ github.workspace }}/bin/box-manifest -c box-compile.json --output-file=compile-manifest.txt --format ansi
                    ${{ github.workspace }}/bin/box-stub -c box-compile.json --output-file=compile-stub.php --resource compile-manifest.txt --resource compile.sbom.xml
                    ${{ github.workspace }}/bin/box-compile -c box-compile.json.dist

            -   # Create a new Release (from a tag)
                name: Create Release from current tag
                if: github.ref_type == 'tag'
                uses: softprops/action-gh-release@v1
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: false
                    draft: true
                    body_path: ${{ github.workspace }}/.changes/${{ github.ref_name }}.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files: |
                        ${{ github.workspace }}/bin/box-manifest.phar
                        ${{ github.workspace }}/bin/box-stub.phar
                        ${{ github.workspace }}/bin/box-compile.phar
                    fail_on_unmatched_files: true
                    tag_name: ${{ github.ref_name }}
