---
name: Release

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    tests:
        uses: ./.github/workflows/unit-tests.yml

    build:
        needs: tests

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - 8.2

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout
                uses: actions/checkout@v4
                with:
                    # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
                    persist-credentials: false

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v3
                with:
                    composer-options: "--prefer-dist"

            -   # Build the current release with artifacts (php archive)
                name: Build Release Artifact
                run: |
                    bin/box-manifest make build stub configure compile -r console-table.txt -r plain.txt -r sbom.json --output-stub stub.php --output-conf box.json.dist -vvv --ansi

            -   # https://github.com/softprops/action-gh-release
                name: Create Release from current tag
                if: github.ref_type == 'tag'
                uses: softprops/action-gh-release@v2
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: false
                    draft: false
                    body_path: ${{ github.workspace }}/.changes/${{ github.ref_name }}.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files: |
                        ${{ github.workspace }}/bin/box-manifest.phar
                    fail_on_unmatched_files: true
                    tag_name: ${{ github.ref_name }}
