---
name: Unit-Tests

on:
    push:
        paths-ignore:
            - 'docs/**'
    pull_request:
        branches: [master]
        paths-ignore:
            - 'docs/**'
    workflow_call:
    workflow_dispatch:

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@ml_v8
        with:
            repository: ${{ github.repository }}
            php-version: "8.2"

    unit_tests:
        needs: lint_files

        name: Unit Tests

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - 8.2
                    - 8.3

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout Code
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
                    fetch-depth: 0

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: phar.readonly=0

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v3
                with:
                    composer-options: "--prefer-dist"

            -   # https://github.com/sebastianbergmann/phpunit/tree/11.4
                name: PHPUnit 11
                run: composer tests:unit
