---
name: Unit-Tests

on:
    pull_request:
        branches: [master]
        paths-ignore:
            - 'docs/**'
    workflow_call:

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}
            php-version: "8.0"

    unit_tests:
        needs: lint_files

        name: Unit Tests

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                php:
                    - 8.1

        steps:
            -   # Git Checkout
                name: Checkout Code
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
                    fetch-depth: 0

            -   # Setup PHP runtime
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: phar.readonly=0
                    tools: phpunit

            -   # Install Composer dependencies
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"

            -   # PHPUnit
                name: PHPUnit
                run: phpunit
